import type { Metadata } from "next";
import "./_styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"!bg-[#F8F8F8]"}>{children}</body>
    </html>
  );
}
